// Copyright (c) 2018 Claus Jørgensen
#pragma once

#define CMD_PING     "PING"
#define CMD_PONG     "PONG"
#define CMD_NICK     "NICK"
#define CMD_USER     "USER"
#define CMD_PASS     "PASS"
#define CMD_VERSION  "VERSION"
#define CMD_ADMIN    "ADMIN"
#define CMD_INFO     "INFO"
#define CMD_PRIVMSG  "PRIVMSG"
#define CMD_NOTICE   "NOTICE"
#define CMD_JOIN     "JOIN"
#define CMD_NAMES    "NAMES"
#define CMD_PART     "PART"
#define CMD_KICK     "KICK"
#define CMD_MODE     "MODE"
#define CMD_TOPIC    "TOIPC"
#define CMD_WHO      "WHO"
#define CMD_MOTD     "MOTD"
#define CMD_RULES    "RULES"
#define CMD_OPER     "OPER"
#define CMD_LIST     "LIST"
#define CMD_LUSERS   "LUSERS"
#define CMD_STATS    "STATS"
#define CMD_USERHOST "USERHOST"
#define CMD_AWAY     "AWAY"
#define CMD_ISON     "ISON"
#define CMD_SUMMON   "SUMMON"
#define CMD_USERS    "USERS"
#define CMD_INVITE   "INVITE"
#define CMD_WHOWAS   "WHOWAS"
#define CMD_WHOIS    "WHOIS"
#define CMD_TIME     "TIME"
#define CMD_LINKS    "LINKS"
#define CMD_MAP      "MAP"
#define CMD_COMMANDS "COMMANDS"
