// Copyright (c) 2018 Claus Jørgensen
#pragma once

#define ERR_UNKNOWNERROR           400
#define ERR_NOSUCHNICK             401
#define ERR_NOSUCHSERVER           402
#define ERR_NOSUCHCHANNEL          403
#define ERR_CANNOTSENDTOCHAN       404
#define ERR_TOOMANYCHANNELS        405
#define ERR_WASNOSUCHNICK          406
#define ERR_TOOMANYTARGETS         407
#define ERR_NOSUCHSERVICE          408
#define ERR_NOORIGIN               409
#define ERR_NORECIPIENT            411
#define ERR_NOTEXTTOSEND           412
#define ERR_NOTOPLEVEL             413
#define ERR_WILDTOPLEVEL           414
#define ERR_BADMASK                415
#define ERR_TOOMANYMATCHES         416
#define ERR_LENGTHTRUNCATED        419
#define ERR_UNKNOWNCOMMAND         421
#define ERR_NOMOTD                 422
#define ERR_NOADMININFO            423
#define ERR_FILEERROR              424
#define ERR_NOOPERMOTD             425
#define ERR_TOOMANYAWAY            429
#define ERR_EVENTNICKCHANGE        430
#define ERR_NONICKNAMEGIVEN        431
#define ERR_ERRONEUSNICKNAME       432
#define ERR_NICKNAMEINUSE          433
#define ERR_SERVICENAMEINUSE       434
#define ERR_BANONCHAN              435
#define ERR_NICKCOLLISION          436
#define ERR_BANNICKCHANGE          437
#define ERR_NICKTOOFAST            438
#define ERR_TARGETTOOFAST          439
#define ERR_SERVICESDOWN           440
#define ERR_USERNOTINCHANNEL       441
#define ERR_NOTONCHANNEL           442
#define ERR_USERONCHANNEL          443
#define ERR_NOLOGIN                444
#define ERR_SUMMONDISABLED         445
#define ERR_USERSDISABLED          446
#define ERR_NONICKCHANGE           447
#define ERR_NOTIMPLEMENTED         449
#define ERR_NOTREGISTERED          451
#define ERR_IDCOLLISION            452
#define ERR_NICKLOST               453
#define ERR_HOSTILENAME            455
#define ERR_ACCEPTFULL             456
#define ERR_ACCEPTEXIST            457
#define ERR_ACCEPTNOT              458
#define ERR_NOHIDING               459
#define ERR_NOTFORHALFOPS          460
#define ERR_NEEDMOREPARAMS         461
#define ERR_ALREADYREGISTERED      462
#define ERR_NOPERMFORHOST          463
#define ERR_PASSWDMISMATCH         464
#define ERR_YOUREBANNEDCREEP       465
#define ERR_YOUWILLBEBANNED        466
#define ERR_KEYSET                 467
#define ERR_INVALIDUSERNAME        468
#define ERR_LINKSET                469
#define ERR_KICKEDFROMCHAN         470
#define ERR_CHANNELISFULL          471
#define ERR_UNKNOWNMODE            472
#define ERR_INVITEONLYCHAN         473
#define ERR_BANNEDFROMCHAN         474
#define ERR_BADCHANNELKEY          475
#define ERR_BADCHANMASK            476
#define ERR_NOCHANMODES            477
#define ERR_BANLISTFULL            478
#define ERR_BADCHANNAME            479
#define ERR_NOULINE                480
#define ERR_NOPRIVILEGES           481
#define ERR_CHANOPRIVSNEEDED       482
#define ERR_CANTKILLSERVER         483
#define ERR_RESTRICTED             484
#define ERR_CANTKICKADMIN          485
#define ERR_NONONREG               486
#define ERR_CHANTOORECENT          487
#define ERR_TSLESSCHAN             488
#define ERR_VOICENEEDED            489
#define ERR_NOOPERHOST             491
#define ERR_NOSERVICEHOST          492
#define ERR_NOFEATURE              493
#define ERR_BADFEATURE             494
#define ERR_BADLOGTYPE             495
#define ERR_BADLOGSYS              496
#define ERR_BADLOGVALUE            497
#define ERR_ISOPERLCHAN            498
#define ERR_CHANOWNPRIVNEEDED      499
#define ERR_UMODEUNKNOWNFLAG       501
#define ERR_USERSDONTMATCH         502
#define ERR_GHOSTEDCLIENT          503
#define ERR_USERNOTONSERV          504
#define ERR_SILELISTFULL           511
#define ERR_TOOMANYWATCH           512
#define ERR_BADPING                513
#define ERR_INVALID_ERROR          514
#define ERR_BADEXPIRE              515
#define ERR_DONTCHEAT              516
#define ERR_DISABLED               517
#define ERR_NOINVITE               518
#define ERR_ADMONLY                519
#define ERR_OPERONLY               520
#define ERR_LISTSYNTAX             521
#define ERR_WHOSYNTAX              522
#define ERR_WHOLIMEXCEED           523
#define ERR_QUARANTINED            524
#define ERR_REMOTEPFX              525
#define ERR_PFXUNROUTABLE          526
#define ERR_BADHOSTMASK            550
#define ERR_HOSTUNAVAIL            551
#define ERR_USINGSLINE             552
#define ERR_STATSSLINE             553
#define ERR_TOOMANYKNOCK           712
#define ERR_CHANOPEN               713
#define ERR_KNOCKONCHAN            714
#define ERR_KNOCKDISABLED          715
#define ERR_NOPRIVS                723
#define ERR_CANNOTDOCOMMAND        972
#define ERR_CANNOTCHANGEUMODE      973
#define ERR_CANNOTCHANGECHANMODE   974
#define ERR_CANNOTCHANGESERVERMODE 975
#define ERR_CANNOTSENDTONICK       976
#define ERR_UNKNOWNSERVERMODE      977
#define ERR_SERVERMODELOCK         979
#define ERR_BADCHARENCODING        980
#define ERR_TOOMANYLANGUAGES       981
#define ERR_NOLANGUAGE             982
#define ERR_TEXTTOOSHORT           983
#define ERR_NUMERIC_ERR            999
